info:
  version: @project.version@
  stage: dev
server:
  port: @server.port@
management:
  metrics:
    export:
      statsd:
        flavor: etsy
        #enabled=true
        #host=localhost
        #port=8125
  security:
    flag: false
spring:
  application:
    name: @project.name@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 3
  flyway:
    schemas: @db.schema@
eventStock:
  pollingEnable: true
deposit:
  polling:
    url: http://localhost:8022/v1/eventsink/deposit
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
    querySize: 100
destination:
  polling:
    url: http://localhost:8022/v1/eventsink/destination
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
    querySize: 100
identity:
  polling:
    url: http://localhost:8022/v1/eventsink/identity
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
    querySize: 100
source:
  polling:
    url: http://localhost:8022/v1/eventsink/source
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
    querySize: 100
wallet:
  polling:
    url: http://localhost:8022/v1/eventsink/wallet
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
    querySize: 100
withdrawal:
  polling:
    url: http://localhost:8022/v1/eventsink/withdrawal
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
    querySize: 100
